#!/usr/bin/env node
// Bundles continents.js, schema.js, and engine.js into a single
// browser-loadable file for the GTM template to `injectScript`.
// No bundler dependency -- a tiny hand-rolled CommonJS module
// registry, since these three files already use plain require()/
// module.exports and nothing else needs to change to run in Node
// (for tests) or, once wrapped this way, in a browser <script> tag.

const fs = require("node:fs");
const path = require("node:path");

const MODULES = [
  { id: "./continents", file: "continents.js" },
  { id: "./schema", file: "schema.js" },
  { id: "./engine", file: "engine.js" },
];

function buildBundle() {
  const moduleBlocks = MODULES.map(({ id, file }) => {
    const source = fs.readFileSync(path.join(__dirname, file), "utf8");
    return `__define(${JSON.stringify(id)}, function (module, exports, require) {\n${source}\n});`;
  }).join("\n\n");

  return `/* Generated by build.js from continents.js, schema.js, and engine.js -- do not edit directly. */
(function (global) {
  "use strict";
  var __modules = {};
  function __define(id, factory) {
    __modules[id] = factory;
  }
  function __require(id) {
    var module = { exports: {} };
    __modules[id](module, module.exports, __require);
    return module.exports;
  }

${moduleBlocks}

  global.VisitorAPIPersonalize = __require("./engine").run;
})(typeof window !== "undefined" ? window : this);
`;
}

function main() {
  const outDir = path.join(__dirname, "dist");
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, "personalize.js"), buildBundle());
  console.log("Wrote dist/personalize.js");
}

main();
