#!/usr/bin/env node
// Bundles the source files into the browser-loadable files that get
// uploaded to cdn.visitorapi.com. No bundler dependency -- a tiny
// hand-rolled CommonJS module registry, since the source files
// already use plain require()/module.exports and nothing else needs
// to change to run in Node (for tests) or, wrapped this way, in a
// browser <script> tag.

const fs = require("node:fs");
const path = require("node:path");

function moduleRegistryPreamble() {
  return `  var __modules = {};
  function __define(id, factory) {
    __modules[id] = factory;
  }
  function __require(id) {
    var module = { exports: {} };
    __modules[id](module, module.exports, __require);
    return module.exports;
  }`;
}

function defineBlocks(modules) {
  return modules
    .map(({ id, file }) => {
      const source = fs.readFileSync(path.join(__dirname, file), "utf8");
      return `__define(${JSON.stringify(id)}, function (module, exports, require) {\n${source}\n});`;
    })
    .join("\n\n");
}

function buildPersonalizeBundle() {
  const modules = [
    { id: "./continents", file: "continents.js" },
    { id: "./schema", file: "schema.js" },
    { id: "./engine", file: "engine.js" },
  ];

  return `/* Generated by build.js from continents.js, schema.js, and engine.js -- do not edit directly. */
(function (global) {
  "use strict";
${moduleRegistryPreamble()}

${defineBlocks(modules)}

  global.VisitorAPIPersonalize = __require("./engine").run;
})(typeof window !== "undefined" ? window : this);
`;
}

function buildAntiFlickerBundle() {
  const modules = [{ id: "./antiflicker", file: "antiflicker.js" }];

  return `/* Generated by build.js from antiflicker.js -- do not edit directly.
 * Meant to be loaded as its own <script src> tag directly in <head>,
 * BEFORE the GTM container snippet -- see README.md. Optionally
 * reads window.visitorApiPersonalizeTimeout; hides elements marked
 * with the fixed .vapi-personalize-target class. */
(function (global) {
  "use strict";
${moduleRegistryPreamble()}

${defineBlocks(modules)}

  var timeoutMs = global.visitorApiPersonalizeTimeout;
  __require("./antiflicker").installAntiFlicker(timeoutMs, {});
})(typeof window !== "undefined" ? window : this);
`;
}

function main() {
  const outDir = path.join(__dirname, "dist");
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, "personalize.js"), buildPersonalizeBundle());
  fs.writeFileSync(path.join(outDir, "personalize-antiflicker.js"), buildAntiFlickerBundle());
  console.log("Wrote dist/personalize.js");
  console.log("Wrote dist/personalize-antiflicker.js");
}

main();
