// Config for the use-case-specific GTM templates generated by
// generate.js. Each entry describes one template: its GTM-facing
// SIMPLE_TABLE columns, and the buildRules() function that turns a
// table row into the generic {field, value, action, selector,
// attribute, content} shape the (unchanged) engine.js already
// understands. See CLAUDE.md for why this replaced a single generic
// template.

const CONDITION_FIELD_OPTIONS = [
  { value: "country", displayValue: "Country" },
  { value: "region", displayValue: "Region" },
  { value: "city", displayValue: "City" },
  { value: "continent", displayValue: "Continent" },
  { value: "currency", displayValue: "Currency" },
  { value: "language", displayValue: "Language" },
  { value: "browser", displayValue: "Browser" },
  { value: "os", displayValue: "OS" },
  { value: "deviceType", displayValue: "Device type" },
];

function conditionColumns() {
  return [
    {
      defaultValue: "country",
      displayName: "Field",
      name: "field",
      type: "SELECT",
      selectItems: CONDITION_FIELD_OPTIONS,
    },
    {
      defaultValue: "",
      displayName: "Value (comma-separated for multiple)",
      name: "value",
      type: "TEXT",
    },
  ];
}

function selectorColumn() {
  return { defaultValue: "", displayName: "CSS selector", name: "selector", type: "TEXT" };
}

function textColumn(name, displayName) {
  return { defaultValue: "", displayName, name, type: "TEXT" };
}

const USE_CASES = [
  {
    id: "replace-image",
    displayName: "VisitorAPI Personalize - Replace Image",
    description: "Swap an image's src based on visitor country, language, currency, etc.",
    tableColumns: [...conditionColumns(), selectorColumn(), textColumn("imageUrl", "New image URL")],
    buildRulesSource: `function buildRules(rawRules) {
  var rules = [];
  for (var i = 0; i < rawRules.length; i++) {
    var row = rawRules[i];
    rules.push({
      field: row.field,
      value: splitValues(row.value),
      action: 'replaceAttribute',
      attribute: 'src',
      selector: row.selector,
      content: row.imageUrl
    });
  }
  return rules;
}`,
    testMockRow: { field: "country", value: "US", selector: ".hero img", imageUrl: "https://example.com/us.jpg" },
    expectedTestRule: {
      field: "country",
      value: ["US"],
      action: "replaceAttribute",
      attribute: "src",
      selector: ".hero img",
      content: "https://example.com/us.jpg",
    },
  },
  {
    id: "replace-link",
    displayName: "VisitorAPI Personalize - Replace Link",
    description: "Swap a link's href based on visitor country, language, currency, etc.",
    tableColumns: [...conditionColumns(), selectorColumn(), textColumn("linkUrl", "New link URL")],
    buildRulesSource: `function buildRules(rawRules) {
  var rules = [];
  for (var i = 0; i < rawRules.length; i++) {
    var row = rawRules[i];
    rules.push({
      field: row.field,
      value: splitValues(row.value),
      action: 'replaceAttribute',
      attribute: 'href',
      selector: row.selector,
      content: row.linkUrl
    });
  }
  return rules;
}`,
    testMockRow: { field: "country", value: "US", selector: "a.cta", linkUrl: "/us/pricing" },
    expectedTestRule: {
      field: "country",
      value: ["US"],
      action: "replaceAttribute",
      attribute: "href",
      selector: "a.cta",
      content: "/us/pricing",
    },
  },
  {
    id: "replace-text",
    displayName: "VisitorAPI Personalize - Replace Text",
    description: "Swap an element's text based on visitor country, language, currency, etc.",
    tableColumns: [...conditionColumns(), selectorColumn(), textColumn("text", "New text")],
    buildRulesSource: `function buildRules(rawRules) {
  var rules = [];
  for (var i = 0; i < rawRules.length; i++) {
    var row = rawRules[i];
    rules.push({
      field: row.field,
      value: splitValues(row.value),
      action: 'replaceText',
      selector: row.selector,
      content: row.text
    });
  }
  return rules;
}`,
    testMockRow: { field: "country", value: "US", selector: ".price", text: "$100 USD" },
    expectedTestRule: {
      field: "country",
      value: ["US"],
      action: "replaceText",
      selector: ".price",
      content: "$100 USD",
    },
  },
  {
    id: "show-hide",
    displayName: "VisitorAPI Personalize - Show/Hide Element",
    description: "Show or hide an element based on visitor country, language, currency, etc.",
    tableColumns: [
      ...conditionColumns(),
      selectorColumn(),
      {
        defaultValue: "show",
        displayName: "Show or hide",
        name: "visibility",
        type: "SELECT",
        selectItems: [
          { value: "show", displayValue: "Show" },
          { value: "hide", displayValue: "Hide" },
        ],
      },
    ],
    buildRulesSource: `function buildRules(rawRules) {
  var rules = [];
  for (var i = 0; i < rawRules.length; i++) {
    var row = rawRules[i];
    rules.push({
      field: row.field,
      value: splitValues(row.value),
      action: row.visibility,
      selector: row.selector
    });
  }
  return rules;
}`,
    testMockRow: { field: "country", value: "US", selector: ".us-banner", visibility: "show" },
    expectedTestRule: {
      field: "country",
      value: ["US"],
      action: "show",
      selector: ".us-banner",
    },
  },
  {
    id: "redirect",
    displayName: "VisitorAPI Personalize - Redirect",
    description: "Redirect a visitor based on their country, language, currency, etc.",
    tableColumns: [...conditionColumns(), textColumn("redirectUrl", "Redirect URL")],
    buildRulesSource: `function buildRules(rawRules) {
  var rules = [];
  for (var i = 0; i < rawRules.length; i++) {
    var row = rawRules[i];
    rules.push({
      field: row.field,
      value: splitValues(row.value),
      action: 'redirect',
      content: row.redirectUrl
    });
  }
  return rules;
}`,
    testMockRow: { field: "country", value: "US", redirectUrl: "https://example.com/us" },
    expectedTestRule: {
      field: "country",
      value: ["US"],
      action: "redirect",
      content: "https://example.com/us",
    },
  },
  {
    id: "replace-attribute",
    displayName: "VisitorAPI Personalize - Replace Attribute (Advanced)",
    description: "Swap any element attribute based on visitor country, language, currency, etc. Use Replace Image or Replace Link instead for the common src/href cases.",
    tableColumns: [
      ...conditionColumns(),
      selectorColumn(),
      textColumn("attribute", "Attribute name (e.g. href, src, alt)"),
      textColumn("attributeValue", "New value"),
    ],
    buildRulesSource: `function buildRules(rawRules) {
  var rules = [];
  for (var i = 0; i < rawRules.length; i++) {
    var row = rawRules[i];
    rules.push({
      field: row.field,
      value: splitValues(row.value),
      action: 'replaceAttribute',
      selector: row.selector,
      attribute: row.attribute,
      content: row.attributeValue
    });
  }
  return rules;
}`,
    testMockRow: { field: "country", value: "US", selector: "video", attribute: "poster", attributeValue: "/us-poster.jpg" },
    expectedTestRule: {
      field: "country",
      value: ["US"],
      action: "replaceAttribute",
      selector: "video",
      attribute: "poster",
      content: "/us-poster.jpg",
    },
  },
];

module.exports = { USE_CASES };
